"""init databases

Revision ID: 556f657afffa
Revises: None
Create Date: 2015-09-29 21:47:34.173967

"""

# revision identifiers, used by Alembic.
revision = '556f657afffa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amphetamine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=255), nullable=True),
    sa.Column('page_value', sa.String(length=255), nullable=True),
    sa.Column('element', sa.String(length=255), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.Column('child_desc', sa.String(length=255), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('parent_desc', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('READ', 'CLICK', 'INPUT'), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amphetamine')
    ### end Alembic commands ###
